# Robot kinematic parameters will be available to all nodes via this shared YAML file
/**:
  ros__parameters:
    hwid: 'USB VID:PID=0483:5740'
    cmd_fmt: '<hhhHHHBH'  # cmd format to send to mainboard
    fbk_fmt: '<hhhhhhBH'  # feedback format from mainboard
    delimiter: 0xAAAA
    # beta: rotation shift between X axis of robot base-frame vs drived direction of wheel (degrees)
    # alpha: angle of wheel (from robot center to the wheel) vs X axis of robot base-frame (degrees)
    motor_01: [240.0, 150.0] # [beta, alpha] in degrees
    motor_02: [0.0, 270.0]
    motor_03: [120.0, 30.0]
    wheel_radius: 0.036  # meters
    center_to_wheel_dis: 0.135   # meters  # distance from center to wheel
    gear_ratio: 18.75            # wheel to motor ratio
    encoder_resolution: 64       # ticks per motor shaft revolution
    pid_control_freq: 100         # Hz
    max_rot_speed: 8.0    # rad/s
    max_xy_speed: 3.0      # m/s # max linear speed in x and y direction
    max_servo_speed: 20000  # max speed command to send to mainboard
    baudrate: 115200
    polarity: 1  # set to -1 if motors spin in reverse
    serial_timeout: 0.05  # seconds
    port: 'auto'  # 'auto' or '/dev/ttyUSB0' etc
    log_level: 'info' # default value, can be overridden in each node

mainboard_controller_node:
  ros__parameters:
    log_level: 'warn'

odometry_node:
  ros__parameters:
    log_level: 'warn'

image_processor_node:
  ros__parameters:
    resolution: [848, 480]      # width, height
    fps: 60                      # camera fps
    exposure_auto: false
    exposure_time: 100           # in microseconds
    white_balance_auto: false
    enable_depth: True           # enable depth stream
    publish_viz_image: False
    publish_viz_fps: 1  # Hz
    publish_viz_resize: 0.5  # factor to resizSe the viz image before publishing
    log_level: 'info'

game_logic_controller_node:
  ros__parameters:
    referee_ip_address: "192.168.3.220"  # IP address of the referee server
    referee_port: 8111                   # Port of the referee server
    # referee_port: 8111
    robot_id: "1_9-tdi"
    log_level: 'info'
